version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  dbadmin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"

  chargebacks:
    build: ./chargebacks_web
    image: chargebacks_web
    volumes:
      - "./chargebacks_web:/home/chargebacks:rw"
    depends_on:
      - db

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
