# Generated by Django 4.0.3 on 2022-04-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('purchase_id', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(choices=[('rc', 'Received'), ('ia', 'In Analysis'), ('ac', 'Accepted'), ('rj', 'Rejected')], default='rc', max_length=2)),
            ],
        ),
    ]
