# Generated by Django 4.0.3 on 2022-04-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='purchase_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
